import time


def _scopes(page):
    scopes = [page]
    try:
        scopes += list(page.frames)
    except Exception:
        pass
    try:
        scopes += list(page.child_frames)
    except Exception:
        pass
    return scopes


def _wait_for(page, selector, max_wait=5):
    for _ in range(max_wait * 2):
        for scope in _scopes(page):
            try:
                loc = scope.locator(selector)
                if loc.count() > 0:
                    return loc.first
            except Exception:
                pass
        time.sleep(0.5)
    return None


def _set_value(loc, value):
    if loc is None:
        return
    value = "" if value is None else str(value).strip()
    if not value:
        return
    try:
        loc.fill(value, timeout=3000)
        return
    except Exception:
        pass
    try:
        loc.evaluate(
            "(el, v) => { el.value = v; "
            "el.dispatchEvent(new Event('input', {bubbles: true})); "
            "el.dispatchEvent(new Event('change', {bubbles: true})); }",
            value,
        )
    except Exception as exc:
        print(f"  WARNING: could not set value: {exc}")


def _select_option(page, selector, text):
    if not text:
        return
    text = str(text).strip()
    loc = _wait_for(page, selector, max_wait=3)
    if loc is None:
        print(f"  WARNING: select not found: {selector}")
        return
    try:
        disabled = loc.evaluate("el => !!(el.disabled || el.readOnly)")
    except Exception:
        disabled = False
    if disabled:
        print(f"  SKIP {selector}: disabled/readonly")
        return
    try:
        opts = loc.locator("option")
        texts = [opts.nth(i).inner_text().strip() for i in range(opts.count())]
    except Exception as exc:
        print(f"  WARNING: could not read options of {selector}: {exc}")
        return
    if not texts:
        print(f"  SKIP {selector}: no options loaded")
        return
    idx = next((i for i, t in enumerate(texts) if t.lower() == text.lower()), None)
    if idx is None:
        idx = next((i for i, t in enumerate(texts) if text.lower() in t.lower()), None)
    if idx is None:
        print(f"  WARNING: no option '{text}' in {selector}: {texts}")
        return
    try:
        loc.select_option(index=idx, timeout=3000)
        print(f"  Selected '{texts[idx]}' in {selector}")
    except Exception as exc:
        print(f"  WARNING: could not select '{text}' in {selector}: {exc}")


def _scroll_to(page, selector):
    """Scroll the given element into view (best-effort)."""
    loc = _wait_for(page, selector, max_wait=3)
    if loc is None:
        return
    try:
        loc.scroll_into_view_if_needed()
        time.sleep(0.3)
    except Exception:
        pass


def _scroll_to_items(page):
    """Scroll to the Items grid section of the requisition form."""
    # Scroll the Insert Row control (bottom of the items grid) into view.
    _scroll_to(page, "#insertrow")
    _scroll_to(page, "#detailBody")
    _scroll_to(page, "#insertItemRowPR")


def _click_edit_icon(page, row_index):
    """Click the Pencil/Edit icon for the given grid row (best-effort).

    The icon is generated by JS when the row is inserted, so its markup is not
    in the static DOM. Try common selectors scoped to the row; if none match,
    log a warning and continue (the row fields may already be editable)."""
    row_selector = f"#detailBody tr[id*='{row_index}']"
    row = _wait_for(page, row_selector, max_wait=3)
    if row is None:
        row = _wait_for(page, "#detailBody tr", max_wait=3)
    if row is None:
        print(f"  WARNING: could not locate grid row {row_index} for edit icon")
        return False

    candidates = [
        "a[title*='Edit' i]",
        "a[class*='edit' i]",
        "button[title*='Edit' i]",
        "button[class*='edit' i]",
        "img[title*='Edit' i]",
        "img[alt*='Edit' i]",
        "span[class*='edit' i]",
        "[class*='edit-icon' i]",
        "[class*='pencil' i]",
        "a[onclick*='edit' i]",
    ]
    for sel in candidates:
        try:
            loc = row.locator(sel).first
            if loc.count() > 0 and loc.is_visible():
                loc.click(timeout=2000)
                print(f"  Clicked edit icon ({sel}) for row {row_index}")
                time.sleep(0.5)
                return True
        except Exception:
            continue
    print(f"  WARNING: edit icon not found for row {row_index}; fields may be directly editable")
    return False


def _click_itembox_sidebutton(page, row_index):
    """After filling Item Code, click the side lookup button.

    Two portal variants exist:

    * New Angular UI: ``<input id=\"itemcodeid\">`` with sibling
      ``<button class=\"btnpopup\"><mat-icon>open_in_new</mat-icon></button>``
      (see ``data/form_dom.html`` angular snippet around ``itemcodeid``).
    * Legacy JSP UI: ``<input id=\"trditemcode0\">`` with a nearby
      ``<div class=\"lookup\">`` / ``<span class=\"lookupImg1\">`` that
      triggers ``openFrame('...popup...')`` (same pattern as Vendor
      ``popup_vendor`` in ``form_dom.html:6867``).

    Tries multiple selectors across all frames/browsers scopes, clicks the
    first visible candidate, waits briefly for the popup/autocomplete to
    appear and best-effort selects the first result.
    """
    # --- Detect which form is present ---
    # Try new Angular first (single search field, no row suffix)
    angular_candidates = [
        "#itemcodeid ~ button.btnpopup",
        "button.btnpopup",
        "button:has(mat-icon:has-text('open_in_new'))",
        "mat-icon:has-text('open_in_new')",
        "//input[@id='itemcodeid']/following::button[contains(@class,'btnpopup')][1]",
        "//mat-icon[text()='open_in_new']/ancestor::button[1]",
        "input#itemcodeid + button",
        "input#itemcodeid ~ button",
    ]
    # Legacy JSP per-row candidates (suffix) — probed live 2026-08-26:
    # row HTML after Insert Row (probe_item_row.py):
    # <input id="trditemcode0" ...><span id="popup_item" onclick="mfgOpenPopup('/mfg/jsp/templates/masters/popup.jsp?entityType=popupmfgitems...','Item List','trditemcode0')"><img src="/TCSFramework/images/find.gif"></span>
    # <span id="popup_itemCode" onclick="mfgCommonAngularPopUp('','','trditemcode',...)"><img src="/.../ammend.gif"></span>
    suf = str(row_index)
    legacy_candidates = [
        f"#trditemcode{suf} >> xpath=following::span[@id='popup_item'][1]",
        f"#trditemcode{suf} >> xpath=following::span[contains(@id,'popup_item')][1]",
        f"#trditemcode{suf} >> xpath=following::span[contains(@onclick,'popupmfgitems')][1]",
        f"#trditemcode{suf} + span#popup_item",
        f"#trditemcode{suf} ~ span#popup_item",
        f"#trditemcode{suf} >> xpath=ancestor::td//span[@id='popup_item']",
        f"span#popup_item[onclick*='popupmfgitems']",
        f"span[id='popup_item'][onclick*='trditemcode{suf}']",
        f"#trditemcode{suf} + div.lookup",
        f"#trditemcode{suf} ~ div.lookup",
        f"#trditemcode{suf} >> xpath=following::div[contains(@class,'lookup')][1]",
        f"#trditemcode{suf} >> xpath=ancestor::td//div[contains(@class,'lookup')]",
        f"#trditemcode{suf} >> xpath=following::span[contains(@class,'lookupImg')][1]",
        f"#trditemcode{suf} >> xpath=following::button[1]",
        "div.lookup[id*='item' i]",
        "div.lookup[onclick*='popup' i]",
        "span.lookupImg1",
        "img[src*='search' i]",
        "div.greyborderimageinput div.lookup",
    ]

    # Helper to try a list of selectors across all scopes
    def _try_candidates(candidates, label):
        for sel in candidates:
            # Handle xpath prefix
            try:
                found = None
                for scope in _scopes(page):
                    try:
                        # Support our custom ">> xpath=" mini-syntax for legacy
                        if ">> xpath=" in sel:
                            base_sel, xpath = sel.split(">> xpath=", 1)
                            base_sel = base_sel.strip()
                            xpath = xpath.strip()
                            if base_sel:
                                base = scope.locator(base_sel).first
                                if base.count() == 0:
                                    continue
                                loc = base.locator(f"xpath={xpath}").first
                            else:
                                loc = scope.locator(f"xpath={xpath}").first
                        else:
                            loc = scope.locator(sel).first
                        if loc.count() == 0:
                            continue
                        # For mat-icon case, click its ancestor button if needed
                        if "mat-icon" in sel and loc.evaluate("el => el.tagName.toLowerCase()") == "mat-icon":
                            # climb to button
                            try:
                                btn = loc.locator("xpath=ancestor::button[1]").first
                                if btn.count() > 0 and btn.is_visible():
                                    loc = btn
                            except Exception:
                                pass
                        if loc.is_visible():
                            found = loc
                            # Robust click
                            try:
                                found.scroll_into_view_if_needed()
                            except Exception:
                                pass
                            clicked = False
                            for _ in range(3):
                                try:
                                    found.click(timeout=2000)
                                    clicked = True
                                    break
                                except Exception:
                                    try:
                                        found.click(force=True, timeout=2000)
                                        clicked = True
                                        break
                                    except Exception:
                                        time.sleep(0.3)
                                        continue
                            if not clicked:
                                try:
                                    found.evaluate("el => el.click()")
                                    clicked = True
                                except Exception:
                                    pass
                            if clicked:
                                print(f"  Clicked itembox sidebutton ({sel}) for row {row_index} [{label}]")
                                time.sleep(0.8)
                                # After click, handle possible popup/autocomplete
                                _handle_item_popup(page, row_index)
                                return True
                    except Exception:
                        continue
            except Exception:
                continue
        return False

    # Try Angular first if its input exists
    has_angular = _wait_for(page, "#itemcodeid", max_wait=1) is not None
    has_legacy = _wait_for(page, f"#trditemcode{suf}", max_wait=1) is not None

    if has_angular:
        if _try_candidates(angular_candidates, "angular"):
            return True
        # fallback to legacy candidates too (in case angular page still has trd* hidden)
    if has_legacy:
        if _try_candidates(legacy_candidates, "legacy"):
            return True
    # If neither form detected, try both lists anyway (mixed portal state)
    if not has_angular and not has_legacy:
        if _try_candidates(angular_candidates, "angular-fallback"):
            return True
        if _try_candidates(legacy_candidates, "legacy-fallback"):
            return True

    print(f"  WARNING: itembox sidebutton not found for row {row_index}; item may need manual lookup or autocomplete")
    return False


def _handle_item_popup(page, row_index):
    """Best-effort handler for the popup/autocomplete that appears after
    clicking the itembox sidebutton or typing the item code.

    Looks for common popup containers (mat-autocomplete-panel, popup, dialog)
    and tries to select the first visible result. Never raises.
    Probed 2026-08-26: item lookup popup is triggered via
    mfgOpenPopup('/mfg/jsp/templates/masters/popup.jsp?entityType=popupmfgitems...')
    which loads an iframe with src containing popupmfgitems; header
    "All Applications" popup (headerIcon popupOpenAction) also matches
    [class*='popup'] but contains CRM/Finance text and must be ignored.
    """
    popup_selectors = [
        "iframe[src*='popupmfgitems']",
        "iframe[src*='popup.jsp']",
        ".mat-autocomplete-panel",
        "[class*='autocomplete']",
        "[class*='popup']",
        "[role='listbox']",
        "[role='dialog']",
        ".ag-popup",
        "div[class*='dropdown']",
        "table[class*='popup']",
        "ul[class*='popup']",
    ]
    try:
        # Short poll for a popup to appear, skipping the header All Applications popup
        popup = None
        for _ in range(8):
            for scope in _scopes(page):
                for sel in popup_selectors:
                    try:
                        loc = scope.locator(sel).first
                        if loc.count() == 0 or not loc.is_visible():
                            continue
                        # Skip header All Applications popup (contains CRM etc.)
                        try:
                            txt = loc.inner_text(timeout=500)[:800]
                            if "CRM" in txt and "Finance and Accounting" in txt and "HelpDesk" in txt:
                                continue  # this is the header popup, not item lookup
                            # Also skip empty popups
                            if not txt.strip():
                                # for iframe, check src instead
                                try:
                                    src = loc.get_attribute("src") or ""
                                    if "popupmfgitems" in src:
                                        popup = loc
                                        break
                                    if not src:
                                        continue
                                except:
                                    continue
                        except:
                            pass
                        popup = loc
                        break
                    except Exception:
                        continue
                if popup is not None:
                    break
            if popup is not None:
                break
            time.sleep(0.5)
        if popup is None:
            # No item popup found — likely onblur validation will handle UOM without popup
            return
        try:
            cls = popup.evaluate("el => el.className || el.getAttribute('src') || ''")
        except:
            cls = ""
        print(f"  Popup detected for row {row_index} ({str(cls)[:80]})")
        time.sleep(0.5)
        # Try to click first selectable item inside popup
        result_selectors = [
            ".mat-option",
            "[role='option']",
            ".mat-autocomplete-panel .mat-option",
            "tr[class*='row']",
            "li[role='option']",
            "td[onclick*='select']",
            "a[onclick*='select']",
            "div[onclick*='select']",
        ]
        for sel in result_selectors:
            try:
                for scope in _scopes(page):
                    try:
                        candidates = scope.locator(sel)
                        n = candidates.count()
                        for i in range(min(n, 5)):
                            cand = candidates.nth(i)
                            try:
                                if cand.is_visible():
                                    txt = cand.inner_text()[:60].replace("\n", " ")
                                    print(f"  Selecting popup result [{sel}] {i}: {txt!r}")
                                    try:
                                        cand.click(timeout=2000)
                                    except Exception:
                                        try:
                                            cand.click(force=True)
                                        except Exception:
                                            cand.evaluate("el => el.click()")
                                    time.sleep(0.6)
                                    return
                            except Exception:
                                continue
                    except Exception:
                        continue
            except Exception:
                continue
        # If no result selector matched, try generic first clickable inside popup
        try:
            first = popup.locator("a, button, tr, li, div").first
            if first.count() > 0 and first.is_visible():
                first.click(timeout=2000)
                print(f"  Clicked generic first element in popup for row {row_index}")
                time.sleep(0.5)
        except Exception:
            pass
    except Exception as exc:
        print(f"  WARNING: popup handler error for row {row_index}: {exc}")


def _verify_item(page, index, expected):
    """Read back the filled Item Code + Required Qty and verify them."""
    suf = str(index)
    ok = True
    code_loc = _wait_for(page, f"#trditemcode{suf}", max_wait=3)
    try:
        actual_code = (code_loc.input_value() if code_loc else "").strip()
    except Exception:
        actual_code = ""
    expected_code = str(expected.get("item_code") or "").strip()
    if expected_code and actual_code != expected_code:
        print(f"  VERIFY FAIL row {index}: item code expected {expected_code!r} got {actual_code!r}")
        ok = False
    else:
        print(f"  VERIFY OK row {index}: item code = {actual_code!r}")

    qty_loc = _wait_for(page, f"#trdqty{suf}", max_wait=3)
    try:
        actual_qty = (qty_loc.input_value() if qty_loc else "").strip()
    except Exception:
        actual_qty = ""
    expected_qty = str(expected.get("qty") or "").strip()
    if expected_qty and actual_qty != expected_qty:
        print(f"  VERIFY FAIL row {index}: qty expected {expected_qty!r} got {actual_qty!r}")
        ok = False
    else:
        print(f"  VERIFY OK row {index}: qty = {actual_qty!r}")
    return ok


def fill_requisition(page, data):
    data = data or {}
    _set_value(_wait_for(page, "#TransactionDate"), data.get("transaction_date"))
    _set_value(_wait_for(page, "[name='trhdesc']"), data.get("description"))
    _select_option(page, "#trhtransubtypelviid", data.get("sub_type"))
    _select_option(page, "#trhtrancatid", data.get("category"))
    _select_option(page, "#trhsiteid", data.get("site"))
    _select_option(page, "#trhaccsiteid", data.get("account_site"))
    _set_value(_wait_for(page, "#partyCode"), data.get("party_code"))
    _set_value(_wait_for(page, "#partyDesc"), data.get("party_desc"))
    _select_option(page, "#trhpartyaddress", data.get("party_address"))
    _set_value(_wait_for(page, "[name='trhremarks']"), data.get("remarks"))
    _set_value(_wait_for(page, "#trhcomments"), data.get("comments"))
    return True


def fill_requisition_items(page, items):
    items = items or []
    if not items:
        return True
    n = len(items)

    # Document flow: scroll to Advanced -> Items section.
    _scroll_to_items(page)

    rows_control = _wait_for(page, "#insertItemRowPR")
    if rows_control is not None:
        try:
            rows_control.fill(str(n))
        except Exception:
            pass

    btn = _wait_for(page, "#insertrow")
    if btn is None:
        print("WARNING: Insert Row button not found")
        return False
    try:
        btn.scroll_into_view_if_needed()
    except Exception:
        pass
    try:
        btn.click()
    except Exception:
        try:
            btn.click(force=True)
        except Exception:
            pass
    try:
        page.wait_for_load_state("networkidle")
    except Exception:
        pass
    time.sleep(2)

    verified = True
    for i, it in enumerate(items):
        suf = str(i)
        # Document flow: click Pencil/Edit icon for the row, then fill.
        _click_edit_icon(page, i)
        _set_value(_wait_for(page, f"#trditemcode{suf}"), it.get("item_code"))
        # Handle Angular new-UI single item-code field (itemcodeid) if present.
        # The Angular form uses one search input for all items; we populate it
        # for the first row and trigger the lookup via its side button.
        if i == 0:
            ang = _wait_for(page, "#itemcodeid", max_wait=1)
            if ang is not None:
                _set_value(ang, it.get("item_code"))
        # Click the side lookup button that validates the item code and
        # populates description/UOM via popup/autocomplete.
        _click_itembox_sidebutton(page, i)
        _set_value(_wait_for(page, f"#trditemdesc{suf}"), it.get("item_desc"))
        _set_value(_wait_for(page, f"#trdacccode{suf}"), it.get("ac_code"))
        _set_value(_wait_for(page, f"#trdreqdate{suf}"), it.get("req_date"))
        _select_option(page, f"#trduomcode{suf}", it.get("uom"))
        _set_value(_wait_for(page, f"#trdpacksize{suf}"), it.get("pack_size"))
        _set_value(_wait_for(page, f"#trdpackquantity{suf}"), it.get("pack_qty"))
        _set_value(_wait_for(page, f"#trdqty{suf}"), it.get("qty"))
        _set_value(_wait_for(page, f"#trdbaseuomcode{suf}"), it.get("base_uom"))
        _set_value(_wait_for(page, f"#trdbaseqty{suf}"), it.get("base_qty"))
        _set_value(_wait_for(page, f"#trditemrate{suf}"), it.get("rate"))
        _set_value(_wait_for(page, f"#trdamount{suf}"), it.get("amount"))
        _set_value(_wait_for(page, f"#trdwtqty{suf}"), it.get("weight_qty"))
        _set_value(_wait_for(page, f"#trdponumber{suf}"), it.get("po_number"))
        _set_value(_wait_for(page, f"#trdcostcentercode{suf}"), it.get("cost_center"))
        _set_value(_wait_for(page, f"#trdremarks{suf}"), it.get("remarks"))
        _select_option(page, f"#trdweightuomcode{suf}", it.get("weight_uom"))
        _select_option(page, f"#trdlocationtypelviid{suf}", it.get("loc_type"))
        _select_option(page, f"#trdlocid{suf}", it.get("loc_id"))
        # Document flow: verify Item Code + Quantity.
        if not _verify_item(page, i, it):
            verified = False
    return verified