/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SystemRouteImport } from './routes/system'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiIndentsRouteImport } from './routes/api/indents'
import { Route as ApiInventoryRouteImport } from './routes/api/inventory'
import { Route as ApiMachinesRouteImport } from './routes/api/machines'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as ApiRefillRouteImport } from './routes/api/refill'
import { Route as ApiRunsRouteImport } from './routes/api/runs'
import { Route as ApiAlertsIndexRouteImport } from './routes/api/alerts/index'
import { Route as ApiAlertsAcknowledgeRouteImport } from './routes/api/alerts/acknowledge'
import { Route as ApiBotsIndexRouteImport } from './routes/api/bots/index'
import { Route as ApiBotsTriggerRouteImport } from './routes/api/bots/trigger'
import { Route as ApiSlipsIndexRouteImport } from './routes/api/slips/index'
import { Route as ApiSlipsDecideRouteImport } from './routes/api/slips/decide'
import { Route as ApiSlipsReceiveRouteImport } from './routes/api/slips/receive'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users/$userId'
import { Route as ApiUsersLoginRouteImport } from './routes/api/users/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndentsRoute = ApiIndentsRouteImport.update({
  id: '/api/indents',
  path: '/api/indents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryRoute = ApiInventoryRouteImport.update({
  id: '/api/inventory',
  path: '/api/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMachinesRoute = ApiMachinesRouteImport.update({
  id: '/api/machines',
  path: '/api/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefillRoute = ApiRefillRouteImport.update({
  id: '/api/refill',
  path: '/api/refill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRoute = ApiRunsRouteImport.update({
  id: '/api/runs',
  path: '/api/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsIndexRoute = ApiAlertsIndexRouteImport.update({
  id: '/api/alerts/',
  path: '/api/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsAcknowledgeRoute = ApiAlertsAcknowledgeRouteImport.update({
  id: '/api/alerts/acknowledge',
  path: '/api/alerts/acknowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsIndexRoute = ApiBotsIndexRouteImport.update({
  id: '/api/bots/',
  path: '/api/bots/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsTriggerRoute = ApiBotsTriggerRouteImport.update({
  id: '/api/bots/trigger',
  path: '/api/bots/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlipsIndexRoute = ApiSlipsIndexRouteImport.update({
  id: '/api/slips/',
  path: '/api/slips/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlipsDecideRoute = ApiSlipsDecideRouteImport.update({
  id: '/api/slips/decide',
  path: '/api/slips/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlipsReceiveRoute = ApiSlipsReceiveRouteImport.update({
  id: '/api/slips/receive',
  path: '/api/slips/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/api/users/$userId',
  path: '/api/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersLoginRoute = ApiUsersLoginRouteImport.update({
  id: '/api/users/login',
  path: '/api/users/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/management': typeof ManagementRoute
  '/requests': typeof RequestsRoute
  '/store': typeof StoreRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/indents': typeof ApiIndentsRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/machines': typeof ApiMachinesRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/refill': typeof ApiRefillRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/alerts/acknowledge': typeof ApiAlertsAcknowledgeRoute
  '/api/bots/trigger': typeof ApiBotsTriggerRoute
  '/api/slips/decide': typeof ApiSlipsDecideRoute
  '/api/slips/receive': typeof ApiSlipsReceiveRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/api/users/login': typeof ApiUsersLoginRoute
  '/api/alerts/': typeof ApiAlertsIndexRoute
  '/api/bots/': typeof ApiBotsIndexRoute
  '/api/slips/': typeof ApiSlipsIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/management': typeof ManagementRoute
  '/requests': typeof RequestsRoute
  '/store': typeof StoreRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/indents': typeof ApiIndentsRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/machines': typeof ApiMachinesRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/refill': typeof ApiRefillRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/alerts/acknowledge': typeof ApiAlertsAcknowledgeRoute
  '/api/bots/trigger': typeof ApiBotsTriggerRoute
  '/api/slips/decide': typeof ApiSlipsDecideRoute
  '/api/slips/receive': typeof ApiSlipsReceiveRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/api/users/login': typeof ApiUsersLoginRoute
  '/api/alerts': typeof ApiAlertsIndexRoute
  '/api/bots': typeof ApiBotsIndexRoute
  '/api/slips': typeof ApiSlipsIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/management': typeof ManagementRoute
  '/requests': typeof RequestsRoute
  '/store': typeof StoreRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/health': typeof ApiHealthRoute
  '/api/indents': typeof ApiIndentsRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/machines': typeof ApiMachinesRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/refill': typeof ApiRefillRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/alerts/acknowledge': typeof ApiAlertsAcknowledgeRoute
  '/api/bots/trigger': typeof ApiBotsTriggerRoute
  '/api/slips/decide': typeof ApiSlipsDecideRoute
  '/api/slips/receive': typeof ApiSlipsReceiveRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/api/users/login': typeof ApiUsersLoginRoute
  '/api/alerts/': typeof ApiAlertsIndexRoute
  '/api/bots/': typeof ApiBotsIndexRoute
  '/api/slips/': typeof ApiSlipsIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bots'
    | '/inventory'
    | '/login'
    | '/machines'
    | '/management'
    | '/requests'
    | '/store'
    | '/system'
    | '/users'
    | '/api/catalog'
    | '/api/health'
    | '/api/indents'
    | '/api/inventory'
    | '/api/machines'
    | '/api/openapi.json'
    | '/api/refill'
    | '/api/runs'
    | '/api/alerts/acknowledge'
    | '/api/bots/trigger'
    | '/api/slips/decide'
    | '/api/slips/receive'
    | '/api/users/$userId'
    | '/api/users/login'
    | '/api/alerts/'
    | '/api/bots/'
    | '/api/slips/'
    | '/api/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bots'
    | '/inventory'
    | '/login'
    | '/machines'
    | '/management'
    | '/requests'
    | '/store'
    | '/system'
    | '/users'
    | '/api/catalog'
    | '/api/health'
    | '/api/indents'
    | '/api/inventory'
    | '/api/machines'
    | '/api/openapi.json'
    | '/api/refill'
    | '/api/runs'
    | '/api/alerts/acknowledge'
    | '/api/bots/trigger'
    | '/api/slips/decide'
    | '/api/slips/receive'
    | '/api/users/$userId'
    | '/api/users/login'
    | '/api/alerts'
    | '/api/bots'
    | '/api/slips'
    | '/api/users'
  id:
    | '__root__'
    | '/'
    | '/bots'
    | '/inventory'
    | '/login'
    | '/machines'
    | '/management'
    | '/requests'
    | '/store'
    | '/system'
    | '/users'
    | '/api/catalog'
    | '/api/health'
    | '/api/indents'
    | '/api/inventory'
    | '/api/machines'
    | '/api/openapi.json'
    | '/api/refill'
    | '/api/runs'
    | '/api/alerts/acknowledge'
    | '/api/bots/trigger'
    | '/api/slips/decide'
    | '/api/slips/receive'
    | '/api/users/$userId'
    | '/api/users/login'
    | '/api/alerts/'
    | '/api/bots/'
    | '/api/slips/'
    | '/api/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotsRoute: typeof BotsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MachinesRoute: typeof MachinesRoute
  ManagementRoute: typeof ManagementRoute
  RequestsRoute: typeof RequestsRoute
  StoreRoute: typeof StoreRoute
  SystemRoute: typeof SystemRoute
  UsersRoute: typeof UsersRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiIndentsRoute: typeof ApiIndentsRoute
  ApiInventoryRoute: typeof ApiInventoryRoute
  ApiMachinesRoute: typeof ApiMachinesRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiRefillRoute: typeof ApiRefillRoute
  ApiRunsRoute: typeof ApiRunsRoute
  ApiAlertsAcknowledgeRoute: typeof ApiAlertsAcknowledgeRoute
  ApiBotsTriggerRoute: typeof ApiBotsTriggerRoute
  ApiSlipsDecideRoute: typeof ApiSlipsDecideRoute
  ApiSlipsReceiveRoute: typeof ApiSlipsReceiveRoute
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
  ApiUsersLoginRoute: typeof ApiUsersLoginRoute
  ApiAlertsIndexRoute: typeof ApiAlertsIndexRoute
  ApiBotsIndexRoute: typeof ApiBotsIndexRoute
  ApiSlipsIndexRoute: typeof ApiSlipsIndexRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/indents': {
      id: '/api/indents'
      path: '/api/indents'
      fullPath: '/api/indents'
      preLoaderRoute: typeof ApiIndentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory': {
      id: '/api/inventory'
      path: '/api/inventory'
      fullPath: '/api/inventory'
      preLoaderRoute: typeof ApiInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/machines': {
      id: '/api/machines'
      path: '/api/machines'
      fullPath: '/api/machines'
      preLoaderRoute: typeof ApiMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refill': {
      id: '/api/refill'
      path: '/api/refill'
      fullPath: '/api/refill'
      preLoaderRoute: typeof ApiRefillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs': {
      id: '/api/runs'
      path: '/api/runs'
      fullPath: '/api/runs'
      preLoaderRoute: typeof ApiRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/': {
      id: '/api/alerts/'
      path: '/api/alerts'
      fullPath: '/api/alerts/'
      preLoaderRoute: typeof ApiAlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/acknowledge': {
      id: '/api/alerts/acknowledge'
      path: '/api/alerts/acknowledge'
      fullPath: '/api/alerts/acknowledge'
      preLoaderRoute: typeof ApiAlertsAcknowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/': {
      id: '/api/bots/'
      path: '/api/bots'
      fullPath: '/api/bots/'
      preLoaderRoute: typeof ApiBotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/trigger': {
      id: '/api/bots/trigger'
      path: '/api/bots/trigger'
      fullPath: '/api/bots/trigger'
      preLoaderRoute: typeof ApiBotsTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slips/': {
      id: '/api/slips/'
      path: '/api/slips'
      fullPath: '/api/slips/'
      preLoaderRoute: typeof ApiSlipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slips/decide': {
      id: '/api/slips/decide'
      path: '/api/slips/decide'
      fullPath: '/api/slips/decide'
      preLoaderRoute: typeof ApiSlipsDecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slips/receive': {
      id: '/api/slips/receive'
      path: '/api/slips/receive'
      fullPath: '/api/slips/receive'
      preLoaderRoute: typeof ApiSlipsReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users/'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/api/users/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/login': {
      id: '/api/users/login'
      path: '/api/users/login'
      fullPath: '/api/users/login'
      preLoaderRoute: typeof ApiUsersLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotsRoute: BotsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MachinesRoute: MachinesRoute,
  ManagementRoute: ManagementRoute,
  RequestsRoute: RequestsRoute,
  StoreRoute: StoreRoute,
  SystemRoute: SystemRoute,
  UsersRoute: UsersRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiIndentsRoute: ApiIndentsRoute,
  ApiInventoryRoute: ApiInventoryRoute,
  ApiMachinesRoute: ApiMachinesRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiRefillRoute: ApiRefillRoute,
  ApiRunsRoute: ApiRunsRoute,
  ApiAlertsAcknowledgeRoute: ApiAlertsAcknowledgeRoute,
  ApiBotsTriggerRoute: ApiBotsTriggerRoute,
  ApiSlipsDecideRoute: ApiSlipsDecideRoute,
  ApiSlipsReceiveRoute: ApiSlipsReceiveRoute,
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
  ApiUsersLoginRoute: ApiUsersLoginRoute,
  ApiAlertsIndexRoute: ApiAlertsIndexRoute,
  ApiBotsIndexRoute: ApiBotsIndexRoute,
  ApiSlipsIndexRoute: ApiSlipsIndexRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
